// BookTrip — UI strings of the book page (owner: book-ui).
//   BOOK_STRINGS = { ru, uk, en }            every key exists in all three languages
//   tb(lang, key, vars)  → string            "{name}" placeholders are replaced from `vars`
//   tbn(lang, key, n, vars) → string         plural forms: key + ".one" | ".few" | ".many" | ".other"
// Missing keys fall back to English, then Russian, then the key itself.

export const BOOK_STRINGS = {
  ru: {
    "nav.label": "Разделы книги",
    "nav.summary": "Пересказ",
    "nav.terms": "Термины",
    "nav.characters": "Персонажи",
    "nav.similar": "Похожие книги",
    "nav.film": "Путешествие в книгу",

    "hero.back": "Назад",
    "hero.coverLabel": "Обложка книги «{title}»",
    "hero.listen": "Слушать пересказ",
    "hero.stop": "Остановить",
    "hero.share": "Поделиться",
    "hero.shareText": "«{title}» на BookTrip: пересказ, персонажи в 3D и мини-фильм.",
    "hero.linkCopied": "Ссылка скопирована — можно отправлять.",
    "hero.copyFailed": "Не получилось скопировать ссылку.",
    "hero.ttsUnsupported": "Ваш браузер не умеет читать вслух.",
    "hero.ttsWait": "Пересказ ещё пишется — чуть-чуть терпения.",
    "hero.demo": "Из библиотеки BookTrip",
    "hero.live": "Создано ИИ специально для вас",
    "hero.original": "В оригинале",
    "hero.themes": "Темы книги",
    "year.bc": "{n} до н. э.",

    "summary.title": "История целиком",
    "summary.readTime": "{n} мин чтения",
    "summary.spoilers": "Со спойлерами",
    "summary.disclaimer": "Пересказ написан искусственным интеллектом — он может ошибаться в деталях. Сверяйтесь с оригиналом.",
    "summary.loading": "ИИ пишет пересказ…",
    "summary.listenShort": "Слушать",

    "terms.title": "Словарь книги",
    "terms.lead": "Имена, места и понятия, без которых в этой истории не обойтись.",
    "terms.filter": "Найти термин",
    "terms.filterPh": "Найти термин…",
    "terms.none": "Ничего не нашлось по запросу «{q}».",
    "terms.loading": "ИИ составляет словарь…",
    "terms.showAll.one": "Показать все {n} термин",
    "terms.showAll.few": "Показать все {n} термина",
    "terms.showAll.many": "Показать все {n} терминов",
    "terms.showAll.other": "Показать все {n} термина",
    "terms.count.one": "{n} термин",
    "terms.count.few": "{n} термина",
    "terms.count.many": "{n} терминов",
    "terms.count.other": "{n} термина",

    "chars.title": "Кто есть кто",
    "chars.lead": "Нажмите на героя — его можно покрутить в 3D.",
    "chars.loading": "ИИ знакомится с персонажами…",
    "chars.empty": "Персонажей пока нет.",
    "chars.open": "{name}: открыть в 3D",
    "chars.figure": "Воксельная фигурка: {name}",
    "chars.count.one": "{n} персонаж",
    "chars.count.few": "{n} персонажа",
    "chars.count.many": "{n} персонажей",
    "chars.count.other": "{n} персонажа",
    "role.protagonist": "Главный герой",
    "role.antagonist": "Антагонист",
    "role.supporting": "Второстепенный",
    "role.minor": "Эпизодический",

    "char.drag": "Потяните, чтобы повернуть",
    "char.viewer": "3D-фигурка: {name}. Потяните, чтобы повернуть.",
    "char.prev": "Предыдущий персонаж",
    "char.next": "Следующий персонаж",
    "char.of": "{i} из {n}",
    "char.aiPortrait": "AI-портрет",
    "char.premium": "премиум",
    "char.portraitLoading": "Нейросеть-художник пишет портрет… Обычно это 10–20 секунд.",
    "char.portraitError": "Портрет не получился. Попробуйте ещё раз чуть позже.",
    "char.portraitRetry": "Попробовать снова",
    "char.portraitAlt": "AI-портрет: {name}",
    "char.portraitNote": "Портрет нарисован ИИ по описанию внешности из книги.",
    "char.portraitNone": "Для этого персонажа портрет пока недоступен.",
    "char.portraitOffTitle": "AI-портреты скоро",
    "char.portraitOffText": "Нейросеть напишет живописный портрет героя по описанию из книги. Функция заработает, как только владелец сайта подключит сервис генерации изображений.",

    "similar.title": "Что читать дальше",
    "similar.lead": "Если эта история зацепила — вот куда отправиться потом.",
    "similar.open": "Открыть «{title}»",
    "similar.loading": "ИИ подбирает похожие книги…",

    "film.title": "Шагните внутрь истории",
    "film.lead": "3D-мини-фильм с озвучкой: вы падаете в книгу и проживаете её главные сцены.",
    "film.presents": "BookTrip представляет",
    "film.play": "Смотреть фильм",
    "film.playLabel": "Смотреть мини-фильм «{title}»",
    "film.pause": "Пауза",
    "film.resume": "Продолжить",
    "film.restart": "Сначала",
    "film.voiceOn": "Озвучка включена",
    "film.voiceOff": "Озвучка выключена",
    "film.fullscreen": "На весь экран",
    "film.exitFullscreen": "Свернуть",
    "film.minutes": "≈ {n} мин",
    "film.withVoice": "с озвучкой",
    "film.preparing": "Готовим декорации…",
    "film.loading": "ИИ пишет сценарий фильма…",
    "film.failed": "Фильм не запустился — возможно, браузер не поддерживает 3D-графику.",
    "film.missing": "Фильм ещё в монтаже — загляните чуть позже.",
    "film.ended": "Конец фильма",
    "film.replay": "Смотреть ещё раз",
    "film.scenesTitle": "Сцены фильма",
    "film.scenes.one": "{n} сцена",
    "film.scenes.few": "{n} сцены",
    "film.scenes.many": "{n} сцен",
    "film.scenes.other": "{n} сцены",

    "video.title": "AI-видео",
    "video.premium": "премиум",
    "video.lead": "Три настоящих 8-секундных клипа, которые видеонейросеть снимет по сценам этой книги.",
    "video.cta": "Создать AI-видео",
    "video.codeTitle": "Премиум-доступ",
    "video.codeText": "Введите код премиум-доступа — и нейросеть снимет три клипа по книге. Съёмка занимает 1–3 минуты.",
    "video.codeLabel": "Код доступа",
    "video.codePh": "Ваш код",
    "video.start": "Снять видео",
    "video.cancel": "Отмена",
    "video.codeEmpty": "Введите код доступа.",
    "video.codeWrong": "Код не подошёл. Проверьте его и попробуйте ещё раз.",
    "video.starting": "Отправляем сценарий на съёмочную площадку…",
    "video.progress": "Нейросеть снимает клипы. Обычно это 1–3 минуты — можно пока почитать.",
    "video.clip": "Клип {n}",
    "video.clipWaiting": "снимается",
    "video.clipReady": "готов",
    "video.elapsed": "{s} с",
    "video.done": "Ваше AI-видео готово",
    "video.doneToast": "AI-видео готово — смотрите в разделе фильма.",
    "video.failed": "Не удалось снять видео. Попробуйте ещё раз чуть позже.",
    "video.timeout": "Съёмка затянулась дольше обычного. Попробуйте ещё раз позже.",
    "video.retry": "Попробовать снова",
    "video.noPrompts": "Для этой книги AI-видео пока недоступно.",
    "video.offTitle": "AI-видео — премиум-функция",
    "video.offText": "Видеонейросеть снимает по книге три кинематографичных клипа — с движением камеры, светом и атмосферой. Функция станет доступна, когда владелец сайта подключит видеосервис.",
    "video.offPoint1": "3 клипа по 8 секунд",
    "video.offPoint2": "Снято по ключевым сценам книги",
    "video.offPoint3": "Готово за 1–3 минуты",
    "video.ok": "Понятно",

    "err.overview": "Пересказ не загрузился",
    "err.characters": "Персонажи не загрузились",
    "err.film": "Фильм не загрузился",
    "err.generic": "Что-то пошло не так. Попробуйте ещё раз.",
    "err.retry": "Повторить",

    "footer.title": "Понравилось путешествие?",
    "footer.lead": "Следующая книга ждёт — любая, какую захотите.",
    "footer.more": "Найти другую книгу",
    "footer.disclaimer": "Пересказы, персонажи и фильмы BookTrip создаёт искусственный интеллект: они помогают познакомиться с книгой, но не заменяют её чтения. Права на произведения принадлежат авторам и правообладателям.",

    "modal.close": "Закрыть",
  },

  uk: {
    "nav.label": "Розділи книги",
    "nav.summary": "Переказ",
    "nav.terms": "Терміни",
    "nav.characters": "Персонажі",
    "nav.similar": "Схожі книги",
    "nav.film": "Подорож у книгу",

    "hero.back": "Назад",
    "hero.coverLabel": "Обкладинка книги «{title}»",
    "hero.listen": "Слухати переказ",
    "hero.stop": "Зупинити",
    "hero.share": "Поділитися",
    "hero.shareText": "«{title}» на BookTrip: переказ, персонажі в 3D і мініфільм.",
    "hero.linkCopied": "Посилання скопійовано — можна надсилати.",
    "hero.copyFailed": "Не вдалося скопіювати посилання.",
    "hero.ttsUnsupported": "Ваш браузер не вміє читати вголос.",
    "hero.ttsWait": "Переказ ще пишеться — трохи терпіння.",
    "hero.demo": "З бібліотеки BookTrip",
    "hero.live": "Створено ШІ спеціально для вас",
    "hero.original": "В оригіналі",
    "hero.themes": "Теми книги",
    "year.bc": "{n} до н. е.",

    "summary.title": "Історія повністю",
    "summary.readTime": "{n} хв читання",
    "summary.spoilers": "Зі спойлерами",
    "summary.disclaimer": "Переказ написав штучний інтелект — він може помилятися в деталях. Звіряйтеся з оригіналом.",
    "summary.loading": "ШІ пише переказ…",
    "summary.listenShort": "Слухати",

    "terms.title": "Словник книги",
    "terms.lead": "Імена, місця й поняття, без яких у цій історії не обійтися.",
    "terms.filter": "Знайти термін",
    "terms.filterPh": "Знайти термін…",
    "terms.none": "Нічого не знайшлося за запитом «{q}».",
    "terms.loading": "ШІ складає словник…",
    "terms.showAll.one": "Показати всі {n} термін",
    "terms.showAll.few": "Показати всі {n} терміни",
    "terms.showAll.many": "Показати всі {n} термінів",
    "terms.showAll.other": "Показати всі {n} терміна",
    "terms.count.one": "{n} термін",
    "terms.count.few": "{n} терміни",
    "terms.count.many": "{n} термінів",
    "terms.count.other": "{n} терміна",

    "chars.title": "Хто є хто",
    "chars.lead": "Натисніть на героя — його можна покрутити в 3D.",
    "chars.loading": "ШІ знайомиться з персонажами…",
    "chars.empty": "Персонажів поки немає.",
    "chars.open": "{name}: відкрити в 3D",
    "chars.figure": "Воксельна фігурка: {name}",
    "chars.count.one": "{n} персонаж",
    "chars.count.few": "{n} персонажі",
    "chars.count.many": "{n} персонажів",
    "chars.count.other": "{n} персонажа",
    "role.protagonist": "Головний герой",
    "role.antagonist": "Антагоніст",
    "role.supporting": "Другорядний",
    "role.minor": "Епізодичний",

    "char.drag": "Потягніть, щоб повернути",
    "char.viewer": "3D-фігурка: {name}. Потягніть, щоб повернути.",
    "char.prev": "Попередній персонаж",
    "char.next": "Наступний персонаж",
    "char.of": "{i} з {n}",
    "char.aiPortrait": "AI-портрет",
    "char.premium": "преміум",
    "char.portraitLoading": "Нейромережа-художник пише портрет… Зазвичай це 10–20 секунд.",
    "char.portraitError": "Портрет не вдався. Спробуйте ще раз трохи згодом.",
    "char.portraitRetry": "Спробувати знову",
    "char.portraitAlt": "AI-портрет: {name}",
    "char.portraitNote": "Портрет намалював ШІ за описом зовнішності з книги.",
    "char.portraitNone": "Для цього персонажа портрет поки недоступний.",
    "char.portraitOffTitle": "AI-портрети незабаром",
    "char.portraitOffText": "Нейромережа напише мальовничий портрет героя за описом із книги. Функція запрацює, щойно власник сайту під'єднає сервіс генерації зображень.",

    "similar.title": "Що читати далі",
    "similar.lead": "Якщо ця історія зачепила — ось куди вирушити потім.",
    "similar.open": "Відкрити «{title}»",
    "similar.loading": "ШІ добирає схожі книги…",

    "film.title": "Ступіть усередину історії",
    "film.lead": "3D-мініфільм з озвученням: ви падаєте в книгу й проживаєте її головні сцени.",
    "film.presents": "BookTrip представляє",
    "film.play": "Дивитися фільм",
    "film.playLabel": "Дивитися мініфільм «{title}»",
    "film.pause": "Пауза",
    "film.resume": "Продовжити",
    "film.restart": "Спочатку",
    "film.voiceOn": "Озвучення ввімкнено",
    "film.voiceOff": "Озвучення вимкнено",
    "film.fullscreen": "На весь екран",
    "film.exitFullscreen": "Згорнути",
    "film.minutes": "≈ {n} хв",
    "film.withVoice": "з озвученням",
    "film.preparing": "Готуємо декорації…",
    "film.loading": "ШІ пише сценарій фільму…",
    "film.failed": "Фільм не запустився — можливо, браузер не підтримує 3D-графіку.",
    "film.missing": "Фільм ще на монтажі — зазирніть трохи згодом.",
    "film.ended": "Кінець фільму",
    "film.replay": "Дивитися ще раз",
    "film.scenesTitle": "Сцени фільму",
    "film.scenes.one": "{n} сцена",
    "film.scenes.few": "{n} сцени",
    "film.scenes.many": "{n} сцен",
    "film.scenes.other": "{n} сцени",

    "video.title": "AI-відео",
    "video.premium": "преміум",
    "video.lead": "Три справжні 8-секундні кліпи, які відеонейромережа зніме за сценами цієї книги.",
    "video.cta": "Створити AI-відео",
    "video.codeTitle": "Преміум-доступ",
    "video.codeText": "Введіть код преміум-доступу — і нейромережа зніме три кліпи за книгою. Зйомка триває 1–3 хвилини.",
    "video.codeLabel": "Код доступу",
    "video.codePh": "Ваш код",
    "video.start": "Зняти відео",
    "video.cancel": "Скасувати",
    "video.codeEmpty": "Введіть код доступу.",
    "video.codeWrong": "Код не підійшов. Перевірте його та спробуйте ще раз.",
    "video.starting": "Надсилаємо сценарій на знімальний майданчик…",
    "video.progress": "Нейромережа знімає кліпи. Зазвичай це 1–3 хвилини — можна поки почитати.",
    "video.clip": "Кліп {n}",
    "video.clipWaiting": "знімається",
    "video.clipReady": "готовий",
    "video.elapsed": "{s} с",
    "video.done": "Ваше AI-відео готове",
    "video.doneToast": "AI-відео готове — дивіться в розділі фільму.",
    "video.failed": "Не вдалося зняти відео. Спробуйте ще раз трохи згодом.",
    "video.timeout": "Зйомка затяглася довше, ніж зазвичай. Спробуйте ще раз пізніше.",
    "video.retry": "Спробувати знову",
    "video.noPrompts": "Для цієї книги AI-відео поки недоступне.",
    "video.offTitle": "AI-відео — преміум-функція",
    "video.offText": "Відеонейромережа знімає за книгою три кінематографічні кліпи — з рухом камери, світлом і атмосферою. Функція стане доступною, коли власник сайту під'єднає відеосервіс.",
    "video.offPoint1": "3 кліпи по 8 секунд",
    "video.offPoint2": "Знято за ключовими сценами книги",
    "video.offPoint3": "Готово за 1–3 хвилини",
    "video.ok": "Зрозуміло",

    "err.overview": "Переказ не завантажився",
    "err.characters": "Персонажі не завантажилися",
    "err.film": "Фільм не завантажився",
    "err.generic": "Щось пішло не так. Спробуйте ще раз.",
    "err.retry": "Повторити",

    "footer.title": "Сподобалася подорож?",
    "footer.lead": "Наступна книга чекає — будь-яка, яку захочете.",
    "footer.more": "Знайти іншу книгу",
    "footer.disclaimer": "Перекази, персонажів і фільми BookTrip створює штучний інтелект: вони допомагають познайомитися з книгою, але не замінюють її читання. Права на твори належать авторам і правовласникам.",

    "modal.close": "Закрити",
  },

  en: {
    "nav.label": "Book sections",
    "nav.summary": "Retelling",
    "nav.terms": "Terms",
    "nav.characters": "Characters",
    "nav.similar": "Similar books",
    "nav.film": "Trip into the book",

    "hero.back": "Back",
    "hero.coverLabel": "Cover of “{title}”",
    "hero.listen": "Listen to the retelling",
    "hero.stop": "Stop",
    "hero.share": "Share",
    "hero.shareText": "“{title}” on BookTrip: a retelling, 3D characters and a mini-film.",
    "hero.linkCopied": "Link copied — ready to send.",
    "hero.copyFailed": "Couldn't copy the link.",
    "hero.ttsUnsupported": "Your browser can't read aloud.",
    "hero.ttsWait": "The retelling is still being written — hang on a moment.",
    "hero.demo": "From the BookTrip library",
    "hero.live": "Made by AI just for you",
    "hero.original": "Original title",
    "hero.themes": "Themes",
    "year.bc": "{n} BC",

    "summary.title": "The whole story",
    "summary.readTime": "{n} min read",
    "summary.spoilers": "Contains spoilers",
    "summary.disclaimer": "This retelling was written by AI and may get details wrong. Check the original.",
    "summary.loading": "AI is writing the retelling…",
    "summary.listenShort": "Listen",

    "terms.title": "The book's glossary",
    "terms.lead": "Names, places and ideas this story can't do without.",
    "terms.filter": "Find a term",
    "terms.filterPh": "Find a term…",
    "terms.none": "Nothing matches “{q}”.",
    "terms.loading": "AI is compiling the glossary…",
    "terms.showAll.one": "Show all {n} term",
    "terms.showAll.other": "Show all {n} terms",
    "terms.count.one": "{n} term",
    "terms.count.other": "{n} terms",

    "chars.title": "Who's who",
    "chars.lead": "Tap a character to spin them around in 3D.",
    "chars.loading": "AI is getting to know the characters…",
    "chars.empty": "No characters yet.",
    "chars.open": "{name}: open in 3D",
    "chars.figure": "Voxel figure of {name}",
    "chars.count.one": "{n} character",
    "chars.count.other": "{n} characters",
    "role.protagonist": "Protagonist",
    "role.antagonist": "Antagonist",
    "role.supporting": "Supporting",
    "role.minor": "Minor",

    "char.drag": "Drag to rotate",
    "char.viewer": "3D figure of {name}. Drag to rotate.",
    "char.prev": "Previous character",
    "char.next": "Next character",
    "char.of": "{i} of {n}",
    "char.aiPortrait": "AI portrait",
    "char.premium": "premium",
    "char.portraitLoading": "The AI artist is painting the portrait… This usually takes 10–20 seconds.",
    "char.portraitError": "The portrait didn't work out. Please try again a little later.",
    "char.portraitRetry": "Try again",
    "char.portraitAlt": "AI portrait of {name}",
    "char.portraitNote": "Painted by AI from the book's description of their looks.",
    "char.portraitNone": "A portrait isn't available for this character yet.",
    "char.portraitOffTitle": "AI portraits are coming",
    "char.portraitOffText": "An image AI will paint a portrait of the character from the book's description. The feature switches on as soon as the site owner connects the image service.",

    "similar.title": "What to read next",
    "similar.lead": "If this story hooked you, here's where to travel next.",
    "similar.open": "Open “{title}”",
    "similar.loading": "AI is picking similar books…",

    "film.title": "Step inside the story",
    "film.lead": "A 3D mini-film with voice-over: you fall into the book and live through its key scenes.",
    "film.presents": "BookTrip presents",
    "film.play": "Watch the film",
    "film.playLabel": "Watch the mini-film “{title}”",
    "film.pause": "Pause",
    "film.resume": "Resume",
    "film.restart": "Restart",
    "film.voiceOn": "Voice-over on",
    "film.voiceOff": "Voice-over off",
    "film.fullscreen": "Full screen",
    "film.exitFullscreen": "Exit full screen",
    "film.minutes": "≈ {n} min",
    "film.withVoice": "with voice-over",
    "film.preparing": "Building the sets…",
    "film.loading": "AI is writing the screenplay…",
    "film.failed": "The film couldn't start — your browser may not support 3D graphics.",
    "film.missing": "The film is still in the edit — check back soon.",
    "film.ended": "The end",
    "film.replay": "Watch again",
    "film.scenesTitle": "Scenes",
    "film.scenes.one": "{n} scene",
    "film.scenes.other": "{n} scenes",

    "video.title": "AI video",
    "video.premium": "premium",
    "video.lead": "Three real 8-second clips that a video AI shoots from this book's scenes.",
    "video.cta": "Create AI video",
    "video.codeTitle": "Premium access",
    "video.codeText": "Enter your premium access code and the AI will shoot three clips from the book. Filming takes 1–3 minutes.",
    "video.codeLabel": "Access code",
    "video.codePh": "Your code",
    "video.start": "Shoot the video",
    "video.cancel": "Cancel",
    "video.codeEmpty": "Enter your access code.",
    "video.codeWrong": "That code didn't work. Check it and try again.",
    "video.starting": "Sending the screenplay to the set…",
    "video.progress": "The AI is shooting your clips. This usually takes 1–3 minutes — feel free to keep reading.",
    "video.clip": "Clip {n}",
    "video.clipWaiting": "filming",
    "video.clipReady": "ready",
    "video.elapsed": "{s} s",
    "video.done": "Your AI video is ready",
    "video.doneToast": "Your AI video is ready — find it in the film section.",
    "video.failed": "The video couldn't be made. Please try again a little later.",
    "video.timeout": "Filming is taking longer than usual. Please try again later.",
    "video.retry": "Try again",
    "video.noPrompts": "AI video isn't available for this book yet.",
    "video.offTitle": "AI video is a premium feature",
    "video.offText": "A video AI shoots three cinematic clips from the book — with camera moves, light and atmosphere. The feature becomes available once the site owner connects the video service.",
    "video.offPoint1": "3 clips, 8 seconds each",
    "video.offPoint2": "Shot from the book's key scenes",
    "video.offPoint3": "Ready in 1–3 minutes",
    "video.ok": "Got it",

    "err.overview": "The retelling didn't load",
    "err.characters": "The characters didn't load",
    "err.film": "The film didn't load",
    "err.generic": "Something went wrong. Please try again.",
    "err.retry": "Try again",

    "footer.title": "Enjoyed the trip?",
    "footer.lead": "The next book is waiting — any one you like.",
    "footer.more": "Find another book",
    "footer.disclaimer": "BookTrip's retellings, characters and films are made by artificial intelligence: they help you get to know a book but don't replace reading it. All rights to the works belong to their authors and rights holders.",

    "modal.close": "Close",
  },
};

const LANGS = ["ru", "uk", "en"];
const pickLang = (lang) => (LANGS.includes(lang) ? lang : "en");

function fill(text, vars) {
  if (!vars) return text;
  return text.replace(/\{(\w+)\}/g, (m, k) => (vars[k] != null ? String(vars[k]) : m));
}

/** Book-page string in `lang` with "{var}" placeholders filled. */
export function tb(lang, key, vars) {
  const l = pickLang(lang);
  const text = BOOK_STRINGS[l][key] ?? BOOK_STRINGS.en[key] ?? BOOK_STRINGS.ru[key] ?? key;
  return fill(text, vars);
}

const pluralRules = {};
/** Plural-aware string: picks `${key}.${category}` for `n` (falls back to `.other`). */
export function tbn(lang, key, n, vars = {}) {
  const l = pickLang(lang);
  let cat = "other";
  try {
    pluralRules[l] ||= new Intl.PluralRules(l);
    cat = pluralRules[l].select(n);
  } catch { /* keep "other" */ }
  const k = BOOK_STRINGS[l][`${key}.${cat}`] != null ? `${key}.${cat}` : `${key}.other`;
  return tb(l, k, { n, ...vars });
}
